title: Streamline ONE
author: Weiwei Yang
email: cheersyang@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a tech blog to share knowledge on the designs of large scale
  computation and distributed file system; and to discuss popular open
  source projects such as HDFS, YARN, Flink, Spark in large production
  clusters.

twitter_username: vvobubble
github_username:  yangwwei

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
